name: build

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
            compiler: latest
        
      - name: Install dependencies
        run:
          brew install bison flex
      
      - name: build
        run: xmake -y